### ISSUE TITLE
Bug - Sorting in archive movies

### ISSUE THREAD

**Issue by Mister3ZE** [madrasthemes/masvideos#20]
Hi,

I have a little bug on sorting in archive movies.

![latest-archive-movies](https://user-images.githubusercontent.com/50516169/57568123-4beb6800-73e3-11e9-9901-1444ce8b2800.jpg)

- 2001-09-12 "Des animaux fous, fous, fous" <- This film is well sorted
- 2001-08-15 "Final fantasy, les créatures de l'esprit" <- This film and the following are not well sorted.

I don't know if it's a MAS Videos plugin or Vodi theme bug. You've my credentials if you want to test it !

**Comment by farookibrahim** [comment]
Hello @Mister3ZE,

Thank you for noticing this issue. We fixed this issue now and updated the fix to your site.

Thanks,
Farook

**Comment by Mister3ZE** [comment]
Ouh yeah ! Greats ! TY !
