### ISSUE TITLE
Advertisement Video

### ISSUE THREAD

**Issue by xe88live** [madrasthemes/masvideos#32]
Hi, I would like to pre-roll advertisement in the video. Could you please guide me how to put it. thanks.

**Comment by farookibrahim** [comment]
Hello @xe88live,

Plugin does not have video advertisement feature however we can achieve this with third party video player plugins.

Regards

**Comment by xe88live** [comment]
which third party video do have this features? could you please help. thanks

**Comment by farookibrahim** [comment]
Hello @xe88live,

Apologies for not getting back to you earlier. You can try third party video player plugin like Ultimate Video Player Wordpress Plugin.

Regards
