### ISSUE TITLE
use the tmdb images instead of downloading them

### ISSUE THREAD

**Issue by phanirithvij** [madrasthemes/masvideos#61]
Is it possible to have the image urls referencing the original URLs from tmdb instead of downloading them?

**Comment by webstractions** [comment]
It would be possible, but why would you want to do that? When you download a poster image, WordPress will make different sizes of the image automatically for you. If you use a poster as a thumbnail, you don't want to use the original size from the TMDB url. I have seen 1200x1800 pixel posters crammed into a thumbnail too many times and it delays the page from loading in quick fashion.

**Comment by phanirithvij** [comment]
You're right, this is more efficient. I don't remember why I opened this issue at that time.
